### ISSUE TITLE
Difference between `Old` folder and top-level `Resource` folder.

### ISSUE THREAD

**Issue by davinchia** [sgotti/k8s-persistent-etcd#2]
Hi @sgotti,

Running into the same problems you ran into trying to get a persistent cluster up. Opening an issue since its the best way to contact you. Can you provide a quick update of the changes you made since? Seems like there is no longer a requirement to use ip address and so the new solution is a `statefulset` of n members where n is the number of etcd pods.

Thanks.

**Comment by sgotti** [comment]
@davinchia `old` was an old solution that used a template to generate yamls but it is ugly and not really needed. It's explained at the end of this post: https://sgotti.me/post/kubernetes-persistent-etcd/

**Comment by davinchia** [comment]
Ah, thanks @sgotti  for the quick reply. Awesome. I was looking at https://hk.saowen.com/a/74678175df97e5cfb694be8f9e47b59833f8e062c7e6669145e4d63a7004c056 which hasn't been updated with the latest solution.

Am I right to say this set up takes care of dead pod/node rescheduling at the kube level. e.g. if a pod dies or a node goes out, the `statefulset` will create the pod and attach it to the correct PV asap. However, this does not take care of disruptions in etcd space, hence the need for the `preStop` hook to remove etcd from the cluster so the pods can properly join.

Is this hook defined in the latest `etcd.yaml` file, or am I missing something? Also, is my understanding correct when I say because the prehook removes the associated etcd node from the cluster if/when pods are killed, any internal etcd churn should not affect applications, since it cluster views this as a decrease in size instead of a quorum loss (unless all members are lost).  

I'm curious how this set up has been working for you in terms of reliability. Can you comment on that? Our use case is somewhat similar to yours in that we are using it to coordinate in-house brokers that are managing queues - data inconsistency can result in hairy situations.

Surprised more people have not shouted about this problem.

**Comment by sgotti** [comment]
> However, this does not take care of disruptions in etcd space, hence the need for the `preStop` hook to remove etcd from the cluster so the pods can properly join.

Can you provide more details? I don't understand what is "disruption in etcd space".

In a real life scenarios with a persistent etcd data if a node crashes or is manually stopped the etcd cluster will continue to work and then the node can rejoin without the need to remove it from the cluster, and the same will happen with k8s. So, as I explained in the post, I don't understand why the node should be removed from the cluster when the pod is stopped (and also it's not guaranteed that the preStop hook is executed: i.e k8s node crashes).



> I'm curious how this set up has been working for you in terms of reliability. Can you comment on that?

My environments are active for months and tested various crash scenarios, also a full k8s cluster restart doesn't gave any problem. Etcd versions upgrades (for example 3.2.2 to 3.3.8) also worked quite well (update the etcd.yaml with the new image version and kill a pod by one or setup automatic statefulset rolling upgrades).

My suggestion is always to try it and stress it with any possible failure.

**Comment by davinchia** [comment]
> Can you provide more details? I don't understand what is "disruption in etcd space".

'disruption in etcd space' - basically operations etcd/raft is aware of e.g. the new member having to rejoin the existing cluster, especially in the worst case when quorum is lost. 

I don't entirely grok,
1) Where is the preStop hook defined?
2) How members rejoin the cluster fine - is this because pod-name + ip is unchanged and so its as though the member disappeared and reappeared?
3) Theoretical read/write behaviour if a partitioning occurs with/without quorum being lost. My intuition is the service endpoint will only return ips from live etcd servers so read/writes will go to live etcd servers.

It'll be great if you can shed light on the above. Otherwise, thanks for the help so far - this is awesome!

**Comment by sgotti** [comment]
> Where is the preStop hook defined?

There's no prestop hook since, as I tried to explain, it doesn't make sense. I asked if you can provide more details since you were the one to talk about this hook.

> How members rejoin the cluster fine - is this because pod-name + ip is unchanged and so its as though the member disappeared and reappeared?

Because the defined etcd service provides consistent dns names (not IPs) that will resolve to the right pod. If the pod is deleted and recreated by the statefulset it'll get a different IP and the DNS name will resolve to it. See the related k8s doc.

> Theoretical read/write behaviour if a partitioning occurs with/without quorum being lost. My intuition is the service endpoint will only return ips from live etcd servers so read/writes will go to live etcd servers.

Talking with the right cluster partition and failing back and handling changed ip is a feature provided by the client. The first connection will retrieve the etcd nodes URLs and then directly use them. For the same reason you aren't forced to use the service name for client communication, the service is only needed for intra etcd nodes discovery. For the client you can just provide the full list of dns urls as endpoints (etcd-0.etcd, etcd-1.etcd, etcd-2.etcd or the fully qualified version so it'll work between namespaces).

**Comment by davinchia** [comment]
Thanks!
